---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gowon
  labels:
    app.kubernetes.io/name: gowon
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: gowon
  template:
    metadata:
      labels:
        app.kubernetes.io/name: gowon
    spec:
      containers:
        - name: gowon
          image: ghcr.io/gowon-irc/gowon:0.1.0-128
          env:
            - name: GOWON_SERVER
              value: oragono:6667
            - name: GOWON_NICK
              value: gowon
            - name: GOWON_USER
              value: gowon
            - name: GOWON_CHANNELS
              value: "#gowon"
            - name: GOWON_CONFIG_DIR
              value: /config
          volumeMounts:
            - name: config
              mountPath: /config
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: trakt-config
